const MyStyle = {
  QuestionBlock: {
    display: "flex",
    flexDirection: "column",
    flexWrap: "wrap",
    borderTop: "2px #e5e7eb solid",
    borderBottom: "2px #e5e7eb solid",
    padding: "7px",
    color: "#4b5563",
  },
  queDiv: {
    fontSize: "1.2em",
  },
  number: {
    backgroundColor: "#5fcf80",
    color: "#fff",
    height: "30px",
    width: "30px",
    display: "inline-block",
    fontSize: "0.8em",
    marginRight: "4px",
    lineHeight: "30px",
    textAlign: "center",
    textShadow: "0 1px 0 rgba(255,255,255,0.2)",
    borderRadius: "100%",
  },
  AnswerStyle: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    border: "2px #cbd5e1 solid",
    width: "30%",
    borderRadius: ".5rem",
    padding: "10px",
    margin: "10px",
    marginTop: "10px",
    // maxHeight: "220px",
    // "overflow-y": "scroll",
  },
  AnswerBlock: {
    padding: "5px",
    fontSize: "1.1em",
    fontWeight: "400",
    margin: "2px",
    color: "#4b5563",
    borderBottom: "1px solid #e2e8f0",
    backgroundColor:"white"
  
  },

  AnswerBlockGray: {
    padding: "5px",
    fontSize: "1.1em",
    fontWeight: "400",
    margin: "2px",
    color: "#4b5563",
    borderBottom: "1px solid #e2e8f0",
    backgroundColor:"#e5e5e5"
  },
  ButtonBlock: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  Button: {
    fontSize: "1.4em",
    borderRadius: ".4em",
    width: "240",
    height: "120",
    padding: "10px",
    textAlign: "center",
    margin: "20px",
    color: "#737373",
    border: "1px solid #fafafa",
    cursor: "pointer",
  },
  FrameBlock: {
    display: "flex",
    flexDirection: "column",
    flexWrap: "wrap",
    margin: "3%",
    width: "60%",
  },
  AppDiv: { display: "flex", flexWrap: "wrap", justifyContent: "center" },
  MessageBlock: {
    fontSize: "1.4em",
    color:"#94a3b8",
    padding: "4px",
    fontFamily: "'Quicksand', sans-serif",
    textAlign: "center",
  },
  MessageBlockHeading: {
    fontSize: "1.6em",
    color:"#1e293b",
    padding: "4px",
    fontFamily: "'Quicksand', sans-serif",
    textAlign: "center",
  },
};
export default MyStyle;
